version: "3.8"
services:
  garmin_api:
    build: ./garmin-api
    container_name: fastapi-application
    volumes:
      - ./data/FIT_files:/code/FIT_files/
    networks:
      - docker-network
  nginx-2:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8085:80
    volumes:
      - ./static_html_homepage/:/usr/share/nginx/html
      - ./user_conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
  clickhouse_db:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - ./data/ch_data:/var/lib/clickhouse/
      - ./data/ch_logs:/var/log/clickhouse-server/
    container_name: clickhouse_db
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge